# fly.toml file generated for eatmail on 2023-03-06T15:11:24+01:00

app = "eatmail"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = [587]
  auto_rollback = true

[[services]]
  internal_port = 8088
  protocol = "tcp"

  [[services.ports]]
    port = 587

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0 
    timeout = "2s"
