# fly.toml file generated for eatmail on 2023-03-06T15:11:24+01:00

app = "eatmail"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = [587]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8088
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 587
