# fly.toml file generated for eatmail on 2023-03-07T09:24:52+01:00

app = "eatmail"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 25

  [[services.ports]]
    port = 465

  [[services.ports]]
    handlers = ["tls"]
    port = 587

  [[services.ports]]
    handlers = ["tls"]
    port = 2525

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
